# Generated by Django 5.0.3 on 2024-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
