# Generated by Django 5.0.3 on 2024-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='vehicle_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
